arch: HRFPN
aux_loss: false
batch_size: 4
dataset: data_case
early_stopping: -1
encoder: resnet101
epochs: 300
factor: 0.1
gamma: 0.6666666666666666
img_ext: .png
input_h: 1024
input_w: 1024
loss: BCEDiceLoss
lr: 0.001
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-06
momentum: 0.9
name: HRFPN_try3
nesterov: false
num_classes: 1
num_workers: 4
optimizer: SGD
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
